version: '2'

services:

  influxdb:
    image: maneeshkumar/influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=jmeter
    networks:
      - mk

  master:
    image: maneeshkumar/jmaster
    container_name: master
    tty: true
    hostname: master
    depends_on:
      - influxdb
    networks:
      - mk
  slave:
    image: maneeshkumar/jserver
    tty: true
    networks:
      - mk

  grafana:
    build:
      context: './grafana'
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
      - master
      - slave
    networks:
      - mk
  
networks:
  mk:
    driver: bridge
